name: 'dbt_bank_snowflake'
version: '1.0.0'
require-dbt-version: ">=1.0.0"

profile: 'dbt_bank_snowflake'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
packages-install-path: "dbt_packages"

models:
  dbt_bank_snowflake:

    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: ephemeral

    marts:
      credit:
        +materialized: table
        +schema: credit
<<<<<<< Updated upstream
=======
      customer:
        +materialized: table
        +schema: customer 
      finance:
        +materialized: table
        +schema: finance
>>>>>>> Stashed changes



snapshots:
  dbt_bank_snowflake:
    +schema: snapshots