dbt_bank_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: hpxuzyt-jg59857
      user: GOGAGABELAIA
      private_key_path: C:\Users\gogag\.dbt\snowflake_private_key.pem
      role: TRANSFORMER_ROLE
      database: BANK_DEV
      warehouse: WH_DBT_DEV
      schema: MARTS
      threads: 4

    ci:
      type: snowflake
      account: hpxuzyt-jg59857
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY') }}"
      role: TRANSFORMER_ROLE
      database: BANK_DEV
      warehouse: WH_DBT_DEV
      schema: "ci_{{ env_var('GITHUB_ACTOR', 'local') }}"
      threads: 4